### ISSUE TITLE
Avoid skipping dots and other special chars

### ISSUE THREAD

**Issue by kgrz** [mookid/diffr#24]
I've put up a repo for demonstrating this: https://github.com/kgrz/diffr-issue

I've seen this happen with dots, hyphens, `=` and some words too. Another example:

![Screenshot 2019-09-10 at 14 44 53](https://user-images.githubusercontent.com/400299/64600923-96a0df00-d3d9-11e9-884c-4b0cc8a1f0a3.png)

**Comment by kgrz** [comment]
I rechecked this with a dark theme, without any extra configs for diffr v0.1.2:

![Screenshot 2019-09-10 at 14 47 40](https://user-images.githubusercontent.com/400299/64601182-1a5acb80-d3da-11e9-93a3-1160ebc278df.png)


Ignore the part with the blue background. That's just search result highlighting in less.

**Comment by mookid** [comment]
Ok, so the issue is this diff:
![image](https://user-images.githubusercontent.com/7757342/64606851-7ff18c80-d3c7-11e9-8b0a-3cc4fce0bf2d.png)

dot is treated as a word of its own, and is part of the LCS in the first diff: 
the . following 10 matches the one following example.

This allows to highlight finer differences: for instance,

```diff
-foo.bar.baz
+foo.bar.baq
```

diffr should highlight baz and baq, rather than the whole lines.


What do you expect the highlighting to be?
